name: Ruby

on: [push,pull_request]

jobs:
  test:
    name: Run Test Suite
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0
    - name: Install dependencies
      run: |
        gem install bundler -v 2.2.3
        bundle install
    - name: Run tests
      run: bundle exec rake
    - name: Run rubocop
      run: bundle exec rubocop
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: photo/timeliner:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}